---
driver:
  name: vagrant

provisioner:
  name: chef_zero

transport:
  forward_agent: true
  username: vagrant

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[waf_testbed::default]
    attributes:
